@extends('backend.doctor.layouts.app')

@section('content')
<div class="container-fluid bg-golden pb-5">
    <div class="row p-4 ">
        <div class="col-lg-6 offset-lg-3 offset-md-2 col-md-8">
            <h3 class="heading text-black text-uppercase"> Doctor Dashboard</h3>
        </div>
    </div>

    <div class="container box-Shadow g-0">
        <div class="row mb-5 g-0">
            <div class="col-md">
                <div class="bg-deepblue doctor-menu">
                     @include('backend.doctor.layouts.sub_layouts.sidebar')
                </div>
            </div>
            <div class="col-md-7 doc-background">
                <div class="doc-content ">
                    <div class="row">
                        <div class="col-md-6"><h4>Zoom Meeting Steps</h4></div>
                        <div class="col-md-6"><p class="text-right">{{date("l")}}, {{date("d")}} {{date("M")}} {{date("Y")}}</p></div>
                    </div>
                    <div class=" bg-white p-3 rounded-2 border">
                        <b>Zoom Setting Steps:</b>
                            <ul>
                                <li><b>Step 1:</b>
                                <p>Please login to gmail account with following credentials <br>or Click <a target="_blank" href="https://mail.google.com/mail/u/0/#inbox"> here </a> to gmail login<br> (This credential is generated by online Docs for you only) <br>
                                    <b>Email:</b>  {{Auth::guard('doctor')->user()->zoom_gmail_id}}</br>

                                    <b>Passsword:</b> Onlinedocs@123 </br>
                                </p>
                                </li>
                                <li><b>Step 2:</b>
                                <p>Check your email inbox recently logged in to step 1 and click the scheduled zoom link and start your meeting.</p>
                                </li>  
                                <b>Note*:</b> Please do not change password given from Online Docs in step 1.
                            </ul>
                        </div>
                   
                </div>
            </div>
            <div class="col-md">
                @include('backend.doctor.pages.profile')
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
@endsection